### ISSUE TITLE
How to set the threshold for M2DP

### ISSUE THREAD

**Issue by ykx9610** [lperdomo/thesis#1]
Hello, I take the liberty of disturbing you. May I ask how to represent the similarity of loop detection and how to set the threshold in the implementation of M2DP? Is Euclidean distance used as the basis for descriptor similarity judgment? Looking forward to your reply, thank you very much.

**Comment by lperdomo** [comment]
Hi, yes, it's the Euclidean norm. If you mean the thresholds used for computing PR curves, after the matching step, all the resulting values are sorted and then themselves are iteratively used in order to plot detailed curves, instead of arbitrarily picking a few threshold values and then plotting something with less data.
